project:
  type: website
  output-dir: docs
  title: "Motus tracking of urban migration stopovers"
  render: 
    - "*.qmd"
    - "!backup.qmd"
  
website: 
  sidebar: 
    style: "floating"
    search: true
    contents: 
      - section: Workflow
        contents: 
          - auto: "[!X]*.qmd"
      - section: Appendicies
        contents: 
          - "XX_details.qmd"
          - "XX_setup.qmd"
          - "XX_citations.qmd"
    tools:
      - icon: github
        href: https://github.com/steffilazerte/urban_motus
  back-to-top-navigation: true
  page-navigation: true
  repo-url: https://github.com/steffilazerte/urban_motus
  repo-actions: [edit, issue]

format:
  html:
    author: "Steffi LaZerte"
    date: today
    toc: true
    toc-depth: 3
    toc-expand: true
    number-sections: true
    number-depth: 1
    lightbox: true
    callout-icon: false
    callout-appearance: minimal

execute: 
  freeze: true
